version: '2'
services:
  db:
    image: postgres
    hostname: db
    networks:
      - ora_code_challenge
  web:
    build: .
    hostname: web
    command: ./run_web.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db
    networks:
      - ora_code_challenge

networks:
  ora_code_challenge:
